# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import pydantic
from typing import Optional
import uuid


class ApiKey(pydantic.BaseModel):
    id: uuid.UUID
    user_id: uuid.UUID
    key_hash: str
    key_prefix: str
    name: str
    last_used_at: Optional[datetime.datetime]
    created_at: datetime.datetime
    expires_at: Optional[datetime.datetime]


class DeviceCode(pydantic.BaseModel):
    device_code: uuid.UUID
    user_code: str
    verification_uri: str
    expires_at: datetime.datetime
    user_id: Optional[uuid.UUID]
    approved: bool
    created_at: datetime.datetime
