name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run ruff
        run: uv run ruff check src/ tests/

      - name: Run mypy
        run: uv run mypy

      - name: Check formatting with black
        run: uv run black --check src/ tests/

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull required images
        run: docker pull python:3.12

      - name: Run unit tests
        run: uv run pytest -v

  sqlc-check:
    name: Verify Database Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sqlc
        run: |
          curl -L https://github.com/sqlc-dev/sqlc/releases/download/v1.30.0/sqlc_1.30.0_linux_amd64.tar.gz | tar xz
          sudo mv sqlc /usr/local/bin/

      - name: Verify sqlc generated code is up-to-date
        run: |
          cd ee
          sqlc generate
          git diff --exit-code raybox/api/db/

  all-checks:
    name: All Checks Passed
    needs: [lint, test, sqlc-check]
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "All CI checks passed successfully!"
