name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run ruff
        run: uv run ruff check src/ tests/

      - name: Run mypy
        run: uv run mypy

      - name: Check formatting with black
        run: uv run black --check src/ tests/

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Configure Podman for rootless mode
        run: |
          # Enable lingering for the user to allow systemd services
          sudo loginctl enable-linger $USER
          # Start podman socket
          systemctl --user start podman.socket
          # Verify socket exists
          ls -la /run/user/$(id -u)/podman/podman.sock || echo "Socket not found"

      - name: Verify Podman installation
        run: |
          podman version
          podman info

      - name: Pull required images
        run: podman pull python:3.12

      - name: Run unit tests
        run: |
          export CONTAINER_HOST=unix:///run/user/$(id -u)/podman/podman.sock
          uv run pytest -v

  all-checks:
    name: All Checks Passed
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "All CI checks passed successfully!"
